name: Reuseable workflow with Semgrep

on:
  workflow_dispatch:

jobs:
  sembrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep

    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v2
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{secrets.SEMGREP_APP_TOKEN}}
